### ISSUE TITLE
Compilable?

### ISSUE THREAD

**Issue by orta** [wireapp/zmessaging-cocoa#1]
Hello there, I've been watching the repo, and download a copy of the source on every release for a quick browse, however it's never compilable. As someone extremely interested in how all the pieces come together it's really difficult to try and understand all the pieces involved.

I know this is a dumb question, but I'd rather ask it as I can't find anything specifically saying that not being able to run the app is part of the plan for OSSing the wire app. So:

* Are you planning on getting this to a point where I, as an OSS rando, can compile (and maybe run against a staging server?)

**Comment by wireswiss** [comment]
Hi Orta,
thanks for the feedback.

The commit https://github.com/wireapp/zmessaging-cocoa/commit/1f444b96357349d15ef6dad648cbe94451570dc7 should fix compilation.
Let us know if you still have problems compiling (please refer to the [readme](https://github.com/wireapp/zmessaging-cocoa/blob/master/README.md) for the required setup).

Please note that at the moment the tests are not running because we excluded some resources required by the tests. We will re-add them in a following release.

As for the backend, we don't currently have plans for providing a separate staging environment for testing.
